### ISSUE TITLE
Release Beta v1.5

### ISSUE THREAD

**Issue by Lockbox313** [Genii-Locorum/brp#10]
**Wounds to to total hit points when hit locations are used.**
The total hit points need to be on the hit point table as things like poison, cold etc will be applied as wounds to total hit points. You can add the total hit point location but as  is listed as locations 1-20  it is ordered after the right leg Also the damage from the locations is not applied.

**Damage Modifier / Damage Bonus**
They are the same thing. I thought I saw something clarifying this but I can't find it.  I am guessing the Damage Bonus at the bottom of the combat is a temporary thing. The value listed under characteristics as listed as a [percentage.](![thp](https://github.com/Genii-Locorum/brp/assets/8994813/a7e5f833-fd81-427e-b44f-7f694b7d1a3f))
![image](https://github.com/Genii-Locorum/brp/assets/8994813/56e85569-29d7-41ef-ae94-d09eb2c98c65)

**Comment by Genii-Locorum** [comment]
Thanks for this.  I've got a fix ready that creates a "General" hit location when you create the chatacter that doesnt show D20 range etc but you can add wounds.
![image](https://github.com/Genii-Locorum/brp/assets/121451824/0d1ea1fe-310a-4749-9567-b228c060e73b)

Ahh, I realise where I went wrong on Damage Mod - leave it with me, that'll be fixed shortly.

**Comment by Genii-Locorum** [comment]
V1.6 now released and sorts this one.
