### ISSUE TITLE
Weapon drag and drop breaks after skills are added to an Actor

### ISSUE THREAD

**Issue by BirDt** [Genii-Locorum/brp#11]
As soon as an Actor is given any skill, any attempts to drag and drop weapons onto the character sheet fail, with this error:
```
Uncaught (in promise) TypeError: game.items.get(...) is undefined
[Detected 1 package: system:brp]
    _BRPonDropItemCreate https://<host>/systems/brp/module/actor/actor-itemDrop.mjs:32
    _onDropItemCreate https://<host>/systems/brp/module/actor/sheets/character.mjs:441
    _onDropItem https://<host>/scripts/foundry.js:71253
    _onDrop https://<host>/scripts/foundry.js:71199
    callback https:/<host>/scripts/foundry.js:65650
    _handleDrop https://<host>/scripts/foundry.js:65701
```

**To replicate:**
1. Create a new actor
2. Create a new skill
3. Create a new weapon
4. Drag & drop the skill onto the actor sheet.
5. Drag & drop the weapon onto the actor sheet. **Expected**: the weapon should show in the Combat tab. **Actual**: the weapon doesn't show and the error above is printed to the web console.

**Comment by Genii-Locorum** [comment]
Thanks for reporting this.

Did you create a combat skill and add it to the weapon item before dropping it on the character sheet?

Can you do game,items in the console and expand the weapon you created down to the "system" section and screenshot that for me please?

**Comment by BirDt** [comment]
Hi, 

Both the weapon and skill are unmodified after being created. Here is the value of game.items, which includes both the weapon and the skill used:
```
[{"name":"test skill","type":"skill","img":"systems/brp/assets/Icons/skills.svg","_id":"vMhHaqilchZ5WwSX","system":{"description":"","gmDescription":"","subType":"","base":0,"xp":0,"profession":0,"personality":0,"personal":0,"effects":0,"baseFormula":{"1":{"stat":"fixed","value":0},"2":{"stat":"fixed","value":0},"Func":"or"},"noXP":false,"category":"cmmnmod","chosen":false,"specialism":false,"group":false,"groupSkills":[],"prsnlty":false,"variable":false,"specName":"","mainName":"test skill","occupation":false,"improve":false},"effects":[],"folder":null,"sort":0,"ownership":{"default":0,"jCHcrYew7ldrQMFe":3},"flags":{"core":{"sourceId":"Item.vMhHaqilchZ5WwSX"}},"_stats":{"systemId":"brp","systemVersion":"11.1.10","coreVersion":"11.315","createdTime":1704793796196,"modifiedTime":1704793796371,"lastModifiedBy":"jCHcrYew7ldrQMFe"}},{"name":"test weapon","type":"weapon","img":"systems/brp/assets/Icons/saber-and-pistol.svg","_id":"kavnA9LVf6MnS0tA","system":{"dmg1":"","dmg2":"","dmg3":"","range1":"","range2":"","range3":"","weaponType":"artillery","db":"none","skill1":"","skill2":"","att":"","special":"none","hands":"none","hp":null,"str":null,"dex":null,"mal":null,"price":"none","enc":null},"effects":[],"folder":null,"sort":0,"ownership":{"default":0,"jCHcrYew7ldrQMFe":3},"flags":{"core":{"sourceId":"Item.kavnA9LVf6MnS0tA"}},"_stats":{"systemId":"brp","systemVersion":"11.1.10","coreVersion":"11.315","createdTime":1704793800925,"modifiedTime":1704793802049,"lastModifiedBy":"jCHcrYew7ldrQMFe"}}]
```

**Comment by Genii-Locorum** [comment]
Thanks

Each weapon needs to have a skill assigned to it (you can assign two).   The skill needs to be a Combat skill for the system to pick it up.

So set up a new skill, change the Category to Combat (the weapon type to the right doesn't matter - Firearm in the screenshot).

Save/close the skill

Now set up the weapon and in the skill selection choose your weapon skill from the drop down.  You can add a second skill - when the weapon is shown on the character sheet the game will pick the highest skill you have in the two skills.  It will also add the weapon skill to the character sheet if you havent got it already.

And this is where the error kicks in - it hunts in the list of game.items for the skill, which in the example you gave hasnt been completed.  An error on my part to not test for this first.  V1.11 of the game will have an test and give an error message on screen saying the weapon doesnt have a skill assigned. 

Please can you test:
1) Create a new skill and set  Category to Combat.  Close the skill.
2) Create a new weapon and select the skill from step 1.

Now drag the weapon to the character sheet.   If you havent added the new skill to the character sheet you should see it on the skills tab and the weapon on the combat tab.

Thanks

Simon
![image](https://github.com/Genii-Locorum/brp/assets/121451824/522167d3-1159-4c97-a465-d15d77c111b1)

**Comment by BirDt** [comment]
Hi,

Giving the weapon a combat category skill does allow it to be added. However, when adding the weapon to an empty sheet, it creates the combat skill twice in the skills tab:
![image](https://github.com/Genii-Locorum/brp/assets/24282498/5bce04b4-a484-4e5d-acfe-e4f82d188880)
If the skill already exists on the sheet, it will create the same skill an additional time. This happens when dragging the weapon onto the sheet after it has already been added (in other words, the number of times the weapon skill shows in the skill list is always n+1, where n is the number of weapons which use that skill).

**Comment by Genii-Locorum** [comment]
OK, V1.11 should be rolled out imminently.  Fingers crossed this is all fixed in it - but please let me know (will keep this open for now).

**Comment by BirDt** [comment]
V1.11 has fixed all the issues in this thread, thanks a bunch!
