### ISSUE TITLE
Initiative rolls

### ISSUE THREAD

**Issue by JurgHenGames** [Genii-Locorum/brp#14]
I can't seem to get initiative-rolls to work at all in this version (Beta 1.12). 

The function to manually change initiative in the combattracker works as intended, so there is a workaround for the issue, abeit a slow one.

**Comment by Genii-Locorum** [comment]
I've done no work on Combat Tracker other than set the initiative to be 1D10 + DEX.  Are you getting any error messages (press F12 for the console).

When I Roll All or roll a specific character I get the dice roll (I use dice-so-nice), can see the chat message and the number shows on the combat tracker

**Comment by JurgHenGames** [comment]
Thank you for replying.
I get the same errormessage if I roll all or for individual actors. I might have a weird setting somewhere I guess, but it "looks right".
I run nothing that should affect the enounter-tracker. (I turned all modules off to test that aswell.)


Uncaught (in promise) Error: Unresolved StringTerm undefined requested for evaluation
    at StringTerm.evaluate (foundry.js:12750:11)
    at Roll._evaluate (foundry.js:10286:42)
    at Roll.evaluate (foundry.js:10250:25)
    at Combat.rollInitiative (foundry.js:21233:18)
    at Combat.rollAll (foundry.js:21282:17)
    at CombatTracker._onCombatControl (foundry.js:86655:36)
    at HTMLAnchorElement.<anonymous> (foundry.js:86592:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by Genii-Locorum** [comment]
Sorry I havent got back to you on this - I've not had time to get to BRP  - but I'm back and will start looking at this now.  Please nudge me if you don't hear anything from me.

**Comment by Genii-Locorum** [comment]
I've had another play and still can't recreate the problem.  A couple of things:
1) What version of Foundry are you on?
2) What release of BRP are you on?

Can you try creating a brand new actor and adding them to a new combat scene.  Do you still get the same issue?

**Comment by JurgHenGames** [comment]
Sorry for the late reply.
BRP is on version Beta 1.12 and Foundry is tha latest one (v11 Stable, Patch 13, Build 315)

Will update BRP to 1.14 today.

**Comment by Genii-Locorum** [comment]
Let me know how it goes and if you still hit the problem.

**Comment by JurgHenGames** [comment]
I tried what you said in 1.12 and it didnt work. 
Updated to 1.14, now it works. 

Lovely! :)
