### ISSUE TITLE
BRP IDs - input needed

### ISSUE THREAD

**Issue by Genii-Locorum** [Genii-Locorum/brp#19]
Hi folks

If you're using this implementation I need your thoughts/input please.

At the moment there's a lot of background checking in the implementation that uses Document IDs (e.g. the skills on a weapon item and then compared to the skills in the game world based on Document ID, which are then compared to the skills in the actor (based on name)).

This means that when importing compendia you need to keep the Document IDs.  The game code also doesn't currently consider compendia since when I wrote it I hadn't even gone there.

So I'm thinking of doing an update - it'll be a chunk of code needing revisiting, but I want to consider a couple of options

1) I am thinking of implementing Call of Cthulhu style IDs in the game so that the linking is done via this rather than document IDs.  Removes the problem of Document IDs.  It will mean updating a lot of items as well and I havent really got my head around migration scripts so it would move a chunk of work to yourselves and may cause issues for your current game implementations.

2) BRP is a very wide game system covering lots of settings.  The compendia I've packed in the game covers all the skills, items etc from the BRUGE rulebook.  I was thinking of removing the compendia from the main game implementation and then packaging it as a separate module or modules.  I could break skills, weapons etc in to multiple modules (e.g. Primitive, Advanced) so you only need to bring in the modules you want (or other people could create modules for their own implementations).  

3) The alternative to "2" is to give every item a series of "eras" and then have in game settings for eras and then you can only use skills, items from the relevant era (as Call of Cthulhu does).

This will really help with the direction of development.

Cheers

Simon

**Comment by Cosmic-Lattee** [comment]
Hello! I been using your system here for a little while now. My thoughts is that having something like a Call of Cthulhu style ID would likely be for the best going forward, and the longer you wait the more painful it will be as people make more items for their games.

Honestly doing both of these might be for the best. That is how Runequest does it as far as having a module for compendiums. Though I think just having a single module would be fine. I imagine that would be less work to maintain anyways.

Just my two cents. :) Loving the system so far.

**Comment by Genii-Locorum** [comment]
Added in 12.1.31
