### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by curtisshipley** [Genii-Locorum/brp#2]
Hi! I've been looking for a BRP plugin for Foundry VTT. Is there still active development on this?

**Comment by Genii-Locorum** [comment]
Hi - this is still an active development, but I'm juggling it with two other systems, a day job and some other hobbies :-)

There is some playtesting due I think to check the direction of travel and when I get feedback on that I will then revisit what needs fixing and what to develop next in the game.

I know at least one person is running a game with it so if you're happy to take a risk with the fact that this is very much a WIP then please feel free to download it and use it.

**Comment by curtisshipley** [comment]
Thanks! In addition to trying it out and providing feedback, what can I do to help? Is there a todo list somewhere?

**Comment by Genii-Locorum** [comment]
A to do list?  That something a proper developer does ;-)  I'm flying by the seat of my pants here and learning as I go.  I think first thing is try it and let me know what's missing, what doesn't work etc and how important it is.  I know I haven't tackled opposed roles, spot rules etc.  I really have only scratched the surface. 

I guess start putting issues here for "things to do" and I will see what I can do. 

And if anyone wants to jump in and help with coding them I'm willing to accept any help I can get.

**Comment by curtisshipley** [comment]
Ok. Will do.
