### ISSUE TITLE
[QOL] Armor Locations

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#21]
So right now when using hit locations and you apply armor you get something like this:

![image](https://github.com/user-attachments/assets/be580189-5475-4bfe-bae5-08e1eeb2d192)

In a case where you have both magical (like the power Protection) and mundane armor you have to add it to all the hit locations creating a massive list like this. 

Maybe being able to directly add to a hit location like you can for NPCs or maybe some place to enter in temporary bonuses. Just something to make it a bit less cluttered. Anyways just some food for thought. :)

**Comment by Genii-Locorum** [comment]
Thanks, let me have a think about this.

Is the issue just the presentation, or is it adding armour/protection multiple times or both?

**Comment by Cosmic-Lattee** [comment]
Yeah it is mostly just a presentation thing. Like it does work it just gets very unwieldy when you have things that give armor bonuses to all locations like this. Especially if it also has normal armor, and perhaps armor from its race as well. While rare you could have three collections of armor sources going at once.

Still mostly just a minor thing and likely can wait till bigger things are tackled. Just wanted to give my two cents. :)

**Comment by Genii-Locorum** [comment]
If I were to somehow collapse/summarise the data (possibly by Hit Location or Armour Type) what is the important info you want to see on the Items tab?  By collapsing it you won't be able to change the carried status, power points etc (as it will no longer be 1 item = 1 line).  Alternatively (and I don't know if I can do this but happy to try) I could look in to effectively having a filter so you only show armour for a specified location or all locations.  This only needs to happen when using Hit Locations as I guess the list is short otherwise.

Just spit balling some ideas

**Comment by Cosmic-Lattee** [comment]
Hm. So I guess in the grand scheme of things you aren't going to be looking at this page all that often.

That said something like this could work:

![Armor Locations](https://github.com/user-attachments/assets/32cdcac2-550a-43c1-8934-8e1312dc3ec9)

The main thing like you said is that you wouldn't be able to edit MP without expanding it. Though I think if I was using something like this I would have my main armor set expanded out and things like the Protection spell closed up since I don't need to edit stuff.

It would be more work but you could have the condensed version show the total penalties to skills and the total ENC, or you could just hide that when it is condensed. 

Anyways just some food for thought. :)

**Comment by Genii-Locorum** [comment]
I've been having a think on this.  Would it make more sense to do the summary/list by hit location?  Is that what people would be more interested in?

I'm thinking that if everything is collapsed it will just list the Hit Locs with armour on, with a summary set of values, and then as you expand each one it swops the hit loc for the list of armour.

If you think by Armour Type is more useful then I will see what I can.

And if you want both, well it may take a while longer :-)

**Comment by Cosmic-Lattee** [comment]
I think that is pretty clever to do it by hit location, I hadn't thought of that!

**Comment by Genii-Locorum** [comment]
Here's a work in progress actual shot (still lots to do on the coding)

You'll get a list of the hit locations which actually has some armour linked to it (Head isn't shown as the character doesn't have a helmet).  The down arrow on the right expands the list but hides the hit location line (to minimise the length of the list). 

In the example Abdomen has been expanded and so the hit location isn't shown but the up arrow is then used to collapse the location list which would mean the armour is hidden and the hit location reappears.

Is this what you want?  Would you rather have the hit location always shown?

![image](https://github.com/user-attachments/assets/c87d7f73-2481-4824-b92f-2d6e2bf2c1d2)

**Comment by Genii-Locorum** [comment]
Done a bit more work on the summary and change the expand/collapse icon

<img width="645" alt="image" src="https://github.com/user-attachments/assets/39e482a9-dfcd-42eb-a01c-aebaf451267d">

**Comment by Cosmic-Lattee** [comment]
That looks great!

**Comment by Genii-Locorum** [comment]
Version 12.1.26 released
