### ISSUE TITLE
[BUG] Critical Damage Doesn't Work

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#22]
Hello!

I am getting this error when I or my player rolls critical damage. Happens both from PC and NPC sheets. 

![image](https://github.com/user-attachments/assets/e1065eae-8bad-444b-b5b6-62646df6a5b2)

No roll shows up in the chat log.

**Comment by Genii-Locorum** [comment]
Thanks, sorted this one (missing this roll evaluate change of syntax).  Will roll it out with next patch - probably this evening when I'm home from work.

**Comment by Genii-Locorum** [comment]
Fixed in Version 12.1.24
