### ISSUE TITLE
Remove / Rename Skill Categories 

### ISSUE THREAD

**Issue by LittleBlueShyGuy** [Genii-Locorum/brp#23]
It would be great to be able to remove / rename the key skill categories on the PC sheet.

My main inspiration for this is Mythras, where you have only two categories; Standard Skills (which everyone has) and Professional Skills (which are only accessible through a character’s professional experience).

Thank you.

**Comment by Lockbox313** [comment]
There already is a  Mythras  module.

**Comment by LittleBlueShyGuy** [comment]
> There already is a  Mythras  module. 

I am aware, and by definition it is a hack of BRP and offers fresh ideas in certain areas.

Given skills are such a HUGE part of the BRP system, it would be great to see more skill customisation options within the universal toolkit module.

**Comment by Genii-Locorum** [comment]
I get both sides of this, whilst I dont have the time to do everything/all house rules etc and Mythras implementation exists, flexibility and adaptability is the cornerstone of BRP.  At the moment the skill categories are hard coded, but I wonder if I should create them as items so a GM can set up their own, name them, change how they calculate.  

Perhaps when I've got the coding done for using items from the compendium rather than the world** I can look at this.   I will add it to the project list but it's probably going to be low priority.

** Hopefully the two weeks Christmas break will give me the chance to sort this, if not before.

**Comment by LittleBlueShyGuy** [comment]
> whilst I dont have the time to do everything

I 100% respect your time and I offer this up as nothing more than a suggestion. If it's something which can be altered, great! But at the end of the day, this is your project and your commitment.

**Comment by Genii-Locorum** [comment]
It's a good suggestion.  The fact is I haven't played BRP in a while and so it's you (the users) who drive the development.

**Comment by Genii-Locorum** [comment]
Right, I've mulled this over and I think I have a plan.

I will add skill "sub-types" - Group Skill, Skill Category and Skill.  People can then create their own Skill Categories, rename them, change the bonuses etc.

But, I want to implement BRP IDs first and then get item list produced using the compendia as well.  So its going to be a while before I do this, but I can see a way to make this work.

**Comment by Genii-Locorum** [comment]
Let me get the BRP ID sorted and then I think it will need some rework/edits of a lot things in the current compendium (which I propose to move to a module) - so help with data entry will be wonderful.

**Comment by Genii-Locorum** [comment]
@LittleBlueShyGuy 

OK, so I've put BRPID (there's got to be a bunch of testing before that goes live and I'm sure I will have to create some migration options (at the moment I've written a couple of macros which should help).

But I've also bundled this request in.  Skill Categories will become their own item where you set the name (all matching is done from BRPIDs or the document ID).  You set your own Simple and Advanced Category Modifiers.

You do need to add the relevant Skill Categories to the actor (and I will make sure they are added to new character creation) - but does this give you what you want?

Still some development, polishing and testing to happen - but the core is done I think.

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/276bba45-985c-4288-bcb6-4136d21033b8">

**Comment by LittleBlueShyGuy** [comment]
Hey, yeah this is looking pretty good!! 

Just to ask, if the skill category has nothing entered in either the 'simple' or 'advanced' drop down menus will it still work? 

I've just tried to test it but it doesn't seem to be working at the moment, but reading your above comment, I'm guessing that's because it's not been implemented quite yet.

**Comment by Genii-Locorum** [comment]
Under the simple Base Stat there is a "None" option.

The default on creation is "none" across the board.

And the game settings still uses the "None, Simple, Advanced" option.


The compendium items should still be there in v 12.1.29.   Version 12.1.30 is on Github as a release but this hasnt been pushed to Foundry yet (got some people testing it as it's a big change).   There is a module which has the compendia, but these are all set up for v12.1.30

**Comment by Genii-Locorum** [comment]
<img width="681" alt="image" src="https://github.com/user-attachments/assets/6882cebb-3ff6-42b4-b7b0-30ba074ec7a1">

**Comment by LittleBlueShyGuy** [comment]
Thanks for that. I foolishly/accidentally updated to the latest version via Foundry and I can't seem to get it to return to the previous version. It's ok. I'll just wait until the update is rolled out proper to test it out. 

Thanks again.

**Comment by Genii-Locorum** [comment]
Can you let me know what version of BRP you're showing in Foundry?  12.1.29 or 12.1.30?

If upgrading has moved you to 12.1.30 then I've got an issue to deal with as I don't want people moving there yet (I will delete the 12.1.30 package).

**Comment by LittleBlueShyGuy** [comment]
It's 12.1.30.

It unfortunately was Foundry which suggested I update. 

I know the risks of updating, don't normally do it until I'm sure... was just too keen to try and test the skill categories haha

**Comment by Genii-Locorum** [comment]
Did you backup your world?

If you did I'd suggest deleting BRP and reinstating your backed up world then manually install the system using this link  "https://github.com/Genii-Locorum/brp/releases/download/Betav1.29/system.json" in Foundry.

Alternatively if you want to keep going then install the module manually in Foundry (https://github.com/Genii-Locorum/basic-role-playing-uge-compendium/releases/download/Betav1/module.json).  There are some migration macros you should run - https://github.com/Genii-Locorum/brp/wiki/Migrating-to-BRP-IDs

**Comment by LittleBlueShyGuy** [comment]
I did backup. Thanks for that. Couldn't find the manifest URL in github!

**Comment by Genii-Locorum** [comment]
Go the release (12.1.29) and you need to click the "Assets" to expand the list, then right click on "system.json" and copy link.

**Comment by Genii-Locorum** [comment]
Added in 12.1.31
