### ISSUE TITLE
[QOL] Being able to see damage/Resolving Attacks

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#24]
Hello!

Two small things. So being able to see what you rolled for damage would be nice. As it is right now there are times that your physical damage bonus might not apply. You can of course just roll it manually but it would be nice to be able to see it.

![image](https://github.com/user-attachments/assets/60b7673d-4ea4-4605-986e-c0424cb38c99)

The other thing is that sometimes the enemy you are fighting cannot dodge, typically when their dodge bonus is reduced below 1%:

![image](https://github.com/user-attachments/assets/35bb7f07-932c-4e67-bfdb-1c8d4c042283)

So maybe letting attacks resolve with no defenses in there might be a workaround for that?

Just some thoughts. :)

**Comment by Genii-Locorum** [comment]
On the second point, if I simply removed the "minimum of 2 rolls needed" would that work for you?

On the damage are you wanting to see the values of each dice rolled (so in your example it might show 2,3,1)?

**Comment by Cosmic-Lattee** [comment]
For the second that sounds fine.

For the first one yeah that would be helpful, and just on with it expanded. I like how it looks now when not expanded out.

**Comment by Genii-Locorum** [comment]
Dice damage - this will go out in the next release

![image](https://github.com/user-attachments/assets/bb8c6efb-7e0b-40c8-853a-f1917028e4d8)

**Comment by Genii-Locorum** [comment]
And Combat Rolls can now be resolved with just 1 roll in them. - will go out in the next release

**Comment by Genii-Locorum** [comment]
Version 12.1.26 released
