### ISSUE TITLE
[BUG] Crushing with a 0 Damage Bonus

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#25]
So if you roll a special with a crushing weapon and you have a 0 Damage Bonus it should add a +1d4 damage bonus instead. The negative damage bonus is working correctly.

![image](https://github.com/user-attachments/assets/8cc01056-c6aa-4e67-b7de-637c35cb0ff4)

Here is where in the rules it talks about that:

![image](https://github.com/user-attachments/assets/e0521dbc-e4a4-4597-8631-18cf7d6c38d1)

It is on page 128 to 129.

**Comment by Genii-Locorum** [comment]
Fixed - will go out in the next release

**Comment by Genii-Locorum** [comment]
Version 12.1.26 released
