### ISSUE TITLE
[BUG] Macro Bar Error

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#26]
Hello!

So I noticed a odd error today. You can make Macros like normal on the macro bar but they cannot be moved after they are created. Further if you create the Macro in the Macro Directory it does not let you place the macro onto the bar.

You can right click the macros and also use them normally.

I can just copy the text of the macro into a new one so it isn't a huge deal if this isn't a easy fix.

**Comment by Genii-Locorum** [comment]
Fixed in next release (thank you to the Call of Cthulhu system for showing me the way

**Comment by Genii-Locorum** [comment]
Version 12.1.26 released
