### ISSUE TITLE
[BUG] Changing Degree of Success in Combat Roll

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#28]
Hello!

I am thinking that something broke with the most recent version of the combat roll. It no longer lowers the type of success you have based off of the other person roll.

![image](https://github.com/user-attachments/assets/22503cd2-10aa-4577-ab50-59dd00257d51)

In this example that Special that the top character got should be a success because the bottom one got a successful dodge.

Thanks for all your hard work! :)

**Comment by Genii-Locorum** [comment]
3 damned little letters.

If you go to module/cards/combat-card.mjs, line 33 and delete "let" at the start.  Ready for the next release
