### ISSUE TITLE
[BUG] Total HP on NPC Sheets with Hit Locations

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#29]
Hello!

One of the recent updates seems to have borked the HP on NPC sheets when hit locations are enabled.

![image](https://github.com/user-attachments/assets/238a242c-302a-4166-b056-f83e3926a646)

Regardless of how much damage is dealt to the locations the total HP isn't reduced.

**Comment by Genii-Locorum** [comment]
Thanks.  On the case

**Comment by Cosmic-Lattee** [comment]
So it looks like it isn't saving damage to the hit locations at all at the moment, which is why it isn't updating the total HP.

**Comment by Genii-Locorum** [comment]
I think I've found the issue - but quick fix if you want to test it.

In npc.mjs, line 247 change 'hpCurr' to 'currHP'

Works for my local implementation

**Comment by Cosmic-Lattee** [comment]
Yep that looks like it fixed it on my end as well!

**Comment by Genii-Locorum** [comment]
Right, will add that to the next release.

**Comment by Genii-Locorum** [comment]
Fixed in 12.1.29
