### ISSUE TITLE
[QOL] Map Grid Scale

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#31]
Hello!

So right now maps are generated with 5 ft for each square in the style of D&D. Since BRP uses meters you could set them to 1 m. That might make some premade maps seem a little off on scale, though to be fair most maps have wonky scale anyways.

**Comment by Genii-Locorum** [comment]
I guess a person broadly takes up a 1m space, happy to set this as the default - appreciating it can be changed on a scene by scene basis.

**Comment by Lockbox313** [comment]
This is  controlled by the Foundry scene not the game system

**Comment by Genii-Locorum** [comment]
Added in 12.1.31
