### ISSUE TITLE
[QOL] Roll Stats on Unlinked Prototype Token Generation

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#32]
Hello again! :)

So another thought I had is it would be cool if when placing unlinked tokens if it would roll random stats for you. The Runequest system currently does this so you could poke around to see if it would be easy to port over.

Now something like this might be a matter of taste so it might be best to have a option to turn it on or off in the system menu.

Finally linked tokens should of course always use the same rolls as in listed on the character sheet.

Thanks!

**Comment by Genii-Locorum** [comment]
Lifted very much from the Call of Cthulhu system (just as I'm more familiar with the code).

Only asks if its an NPC, it's not linked to the Actor and the BaseStats Random or Average columns have got some entries.


<img width="939" alt="image" src="https://github.com/user-attachments/assets/6307b0f2-3a35-4c04-b77e-b3eb086ee65e">

**Comment by Genii-Locorum** [comment]
Added in 12.1.31
