### ISSUE TITLE
[QOL] Characteristics and Diseases

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#33]
So in BRP the rules for diseases (page 146) involve you rolling CON times a variety of numbers depending on things like how clean of a environment you are in. So it can vary from CON x 1 to CON x 5.

Systems like Runequest do this for all characteristics allowing characteristic tests with harder difficulties. So it might be worthwhile to let you do that for all characteristics if you are going to have to work it out for CON.

Just some food for thought!

**Comment by Genii-Locorum** [comment]
Would you always use entering a difficulty Value (*1, *2) rather than entering a Diff Level (Easy, Medium) for Characteristic Rolls?

Or does this need to be something where you can select either option?

**Comment by Lockbox313** [comment]
Characteristic rolls are a mess.  In most of the other BRP systems it is just a straight multiplier.  If you take look at pgs  110, 113 and 146 it is all mixed up with the BRUGE difficulty system.

pg 110. States that the difficulty is represented by the multiplier assigned by the GM and then directs to pg 113.
For these situations, use a characteristic roll, with a  chance of your character’s characteristic multiplied by a number. CON, 
INT, DEX, and CHA are common characteristics to use, and most  characteristic rolls have a ×5 multiplier. Depending on the difficulty of the action, your gamemaster may use a higher or lower multiplier. 


pg 113
Difficulty levels are: Automatic, Easy, Average, Difficult, and Impossible. 

- Easy characteristic rolls use a multiplier of ×10 or double the normal characteristic roll
- Average characteristic rolls use a multiplier of ×5 and are the default on your character sheet.
- To determine the skill rating or characteristic rating for a Difficult action, divide the appropriate skill or characteristic roll in half (round up)


Pg 145 Choking, Drowning, and Asphyxiation  and pg 147 Disease use the descending scale.

I guess the way easiest way is a drop down with 10x to 0.5x default to x5.  I think there are to may options for radio buttons.

**Comment by Genii-Locorum** [comment]
Agreed - consistency would be nice (and so much easier to code)

There is a game setting to use multipliers rather than set difficulty levels.  It would be easy to force characteristic rolls to use the multiplier all the time or perhaps let you select a drop down or a multiplier (if multiplier populated then select that, otherwise use the dropdown option).

I also wonder whether I should add some customisation so the GM can set the multiplier for the different difficulties at a game level

**Comment by Cosmic-Lattee** [comment]
You could do something like this: 

![image](https://github.com/user-attachments/assets/56ba45af-78dd-420b-aef2-d083a65169b8)

My thinking here in BRP style games I generally see the x1, x2, x3, x4, & x5 modifiers generally. 95% of the time you are just going to be doing a x5 modifier so you could leave that as the default.

You leave the average, easy, difficult modifiers there. That is how you get that x10 since it would take the x5 number from the first option then multiple it by 2 for a easy check.

I am always for the option to be able to do custom modifiers though I don't think in this case it would be used by pretty much anyone. I can't think of times you would want to set the numbers to be anything other than x1 to x5. Though I could be wrong!

**Comment by Genii-Locorum** [comment]
@Cosmic-Lattee @Lockbox313 

I want to keep it simple for users - so having two selections that interact feels complicated (set one to *5 and the other to easy).

What I could do is add two additional Difficulty levels for characteristic rolls only so you would get the following options

Easy (*10)
Average (*5)
Tricky (*4) - happy for a different name
Awkward (*3) - happy for a different name
Difficult (*2.5)
Hard (*2)
Extreme (*1)
Impossible (=1%)

Alternatively characteristic rolls don't use the Difficulty dropdown - you just enter a mutliplier

So in both cases there's only one input box

What do you think?

**Comment by Cosmic-Lattee** [comment]
So if we were going to do a single box I would rather it be a drop down myself, or at the very least have x5 be prewritten into the field if it is editable.

I wouldn't want to be in a situation that I have to write something in each time I do a characteristic check.

If you go with the drop down you could just forget the names and just put in the multiplication value. Regardless though the names you have are good if you want to keep them.

**Comment by Genii-Locorum** [comment]
Will this work?  Default is "Average (*5)"

For non-stat rolls you get the usual difficulties.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/06ccd892-e896-4ab9-9f81-1e7c66ccf15f">

![image](https://github.com/user-attachments/assets/bd62e81d-9670-4689-9cfd-8d9aab0e1c5e)

**Comment by Cosmic-Lattee** [comment]
That looks good to me!

**Comment by Genii-Locorum** [comment]
Now gone live with release 12.1.32
