### ISSUE TITLE
[BUG] Skills Look Wonky

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#35]
Hello!

![image](https://github.com/user-attachments/assets/03759d04-faf0-494b-9a0e-747be867ba50)

Skills are now going all the way to the bottom of the page. You can still click on them so it is mostly a visual thing.

**Comment by Genii-Locorum** [comment]
Thanks - this will be fixed in next release (this may take a bit as there's a couple of big things I'm working on).

However short term fix is to change row 332 in brp.css (.brp .bottom-panel) to   height: calc(100% - 330px);
