### ISSUE TITLE
[BUG] Items are Wonky

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#37]
Hello!

![image](https://github.com/user-attachments/assets/e2981a26-02f9-4999-8b27-adc096027fdb)

The items are a bit messed up at the moment after the last update.

**Comment by Genii-Locorum** [comment]
Thanks - fixed in next release.  Quick fix if you want it now.  On brp.css file go to: 
.brp .gear-tab-grid 

In grid-template-columns change max-content to 250px:

  grid-template-columns: 250px 100px 100px 40px 35px 75px 30px;
