### ISSUE TITLE
The fields for skills with specialities seem to be in the wrong order.

### ISSUE THREAD

**Issue by Lockbox313** [Genii-Locorum/brp#39]
If I create skill called Computer and then mark it as specialism I get this.
![image](https://github.com/user-attachments/assets/587ece0c-3e87-4b76-afff-ca0f6a309655)

But to get it to display correctly I need to switch the fields. 
![image](https://github.com/user-attachments/assets/fd135e1c-5021-40da-8568-651126fcf2ed)

**Comment by Lockbox313** [comment]
It appears that this only happens when the Specialism Chosen is active.  What is the purpose of this I was under the impression this controls if dialog appears asking for the specialty when the skill is dragged to the sheet.

**Comment by Lockbox313** [comment]
Anyone that has seen a paper sheet or read the rules will expect these type of skills to be grouped together. I would prefer the 3rd option people who have used the paper will ask me as GM why they are not grouped and if they are going placed alphabetically I would create new skills as it involves less steps.  I was creating pregens for Cthulhu rising and was entering skills with specializations they were jumping all over the place. There is Electronics(Security) and Computer(Security) and they where placed together.  Sorry if this rambling or incoherent. 

![image](https://github.com/user-attachments/assets/ae945790-aa57-4998-b15c-3e2c51016648)

**Comment by Genii-Locorum** [comment]
Not rambling at all - will get on to this tomorrow morning and if things go well will try to push a release out tomorrow (which also has cultures in)

**Comment by Genii-Locorum** [comment]
Hopefully this will do..
<img width="538" alt="image" src="https://github.com/user-attachments/assets/6ffe9328-9143-4049-8b9f-fc260168e99f">

I'll push it out in the next release
