### ISSUE TITLE
[Minor] [QOL] Skill Category Bonuses/Penalties 

### ISSUE THREAD

**Issue by Cosmic-Lattee** [Genii-Locorum/brp#40]
Hello!

So I know in the long run the plan is for the armor penalty to be done automatically, but until then something that would make it easier to track would be the ability to do arbitrary bonuses or penalties to skill categories.

Outside of armor there might be other edge cases for this, but that is the major one. Once armor penalties are working then this is a less needed feature hence why I labeled it as minor.

Thanks! :)

**Comment by Genii-Locorum** [comment]
Ready to go out in the next release.  Click on the skill category on the character sheet to open the item.  You'll now see the calculated score along with the option to enter a modifier.

<img width="708" alt="image" src="https://github.com/user-attachments/assets/c03d1d46-6e5c-4ac8-b9da-b8c50ef80ca8" />
