### ISSUE TITLE
Beta 1.1 Dragging Weapons not working

### ISSUE THREAD

**Issue by Lockbox313** [Genii-Locorum/brp#5]
Draging Weapons results in an error message.

actor-itemDrop.mjs:27 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at BRPactorItemDrop._BRPonDropItemCreate (actor-itemDrop.mjs:27:59)
    at BRPCharacterSheet._onDropItemCreate (character.mjs:417:48)
    at BRPCharacterSheet._onDropItem (foundry.js:71253:17)
_

All of the weapon items default skill options are  set to grenade, If the skill option is changed the weapon can be dragged.

**Comment by Genii-Locorum** [comment]
When importing the Compendia did you tick the "Keep Document IDs"?

**Comment by Lockbox313** [comment]
No I didn't.  Just deleting the items and  importing again with  the checkbox didn't seem to work. I had to delete the world and do the import again to get it working.  Something minor I noticed the  Flail, Morningstar damage is set to 1D10+11D6
﻿

**Comment by Genii-Locorum** [comment]
Thanks, I've fixed the damage - will get updated in next release.

Did the weapon drag and drop work now?

**Comment by Lockbox313** [comment]
Yes it did.  If I get a chance over the weekend I will try setting up a
full sheet over the weekend

**Comment by Lockbox313** [comment]
> Thanks, I've fixed the damage - will get updated in next release.
> 
> Did the weapon drag and drop work now?

Yes it did.  If I get a chance over the weekend I will try setting up a
full sheet over the weekend
