### ISSUE TITLE
Newly created actor cannot be opened

### ISSUE THREAD

**Issue by WisdomOfWombats** [Genii-Locorum/brp#6]
I installed the system, created a world, imported the compendia, then created an actor. But that actor cannot be opened.
I have no idea whats going on...

**Comment by Genii-Locorum** [comment]
Can you open the console (F12) and send me a screenshot of any red sections.   Thanks

**Comment by WisdomOfWombats** [comment]
Found the following error:

foundry.js:753 Error: An error occurred while rendering BRPCharacterSheet 60. ENOENT: no such file or directory, open '/home/ubuntu/foundrydata/Data/systems/BRP/templates/actor/character-sheet.html'
    at a.<anonymous> (foundry.js:7678:41)
    at a.value (socket.js:532:17)
    at a.value (socket.js:459:22)
    at L.emit (index.mjs:136:20)
    at manager.js:207:18
onError @ foundry.js:753
(anonymous) @ foundry.js:5771
Promise.catch (async)
render @ foundry.js:5769
render @ foundry.js:7111
_onClickEntryName @ foundry.js:70219
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by Genii-Locorum** [comment]
I think the issue is the folder name "home/ubuntu/foundrydata/Data/systems/BRP/" - should be "home/ubuntu/foundrydata/Data/systems/brp/"

Is this something you got to name (BRP rather than brp)?  Can you manually rename it?  If its not then it's my side and I need to do some digging

**Comment by Genii-Locorum** [comment]
Sorted (and thank you for your help testing it Wisdom).   Fix made and pushed out in V1.3 now.
