### ISSUE TITLE
Variable bases for skills do not seem to be working

### ISSUE THREAD

**Issue by Lockbox313** [Genii-Locorum/brp#7]
It is not working with dodge. I tried to add exp, and profession points to see if that would trigger the base calculation but it didn't. Changing the DEX value does not trigger it either.  I also created a new skill and it didn't work with that either.
![variable_base_error](https://github.com/Genii-Locorum/brp/assets/8994813/a6b41224-97b7-459e-a0c6-4b13da19c74a)

**Comment by Genii-Locorum** [comment]
I havent coded that in yet on the skill drop - just built the data in to the skill item for adding it later.  I will start a backlogs list here and add it to that.

**Comment by Lockbox313** [comment]
👍

**Comment by Genii-Locorum** [comment]
@Lockbox313  This is now sorted in V1.4 along with a few other bits added:
Updated item drop so base skill scores are automatically calculated
Autocalc for Max HP, PP & FP added
Added a Game Setting to allow characters to have enhanced HP
Added a flat modifier to characters on Characteristics tab to increase HP (driven by superpowers)

Please can you test and see if you're happy with it before I close this.

**Comment by Lockbox313** [comment]
Wow that was fast.

From a quick run through
>Updated item drop so base skill scores are automatically calculated
Yes

>Autocalc for Max HP, PP & FP added
Yes

>Added a Game Setting to allow characters to have enhanced HP
Yes

>Added a flat modifier to characters on Characteristics tab to increase HP (driven by superpowers)
Yes

>Once the skill has dropped then changing the stats does not alter the base 
Yes
>(this was something I confirmed with the >authors).
hmmmm

**Comment by Genii-Locorum** [comment]
Thanks.  I'll close the issue.
