### ISSUE TITLE
Nice to have: clicking on a skill on the character sheets opens the skill

### ISSUE THREAD

**Issue by WisdomOfWombats** [Genii-Locorum/brp#8]
This is really just nice to have:
- The user clicks on a skill on the character sheet
- The system open the skill dialog (same as right-click and selecting view)
Unless of course, the left click is going to be reserved for something else.

**Comment by Lockbox313** [comment]
Left click will more than likely roll the skill unless it is edit more.

**Comment by Genii-Locorum** [comment]
Yeah, my plan was left click to make a skill roll.    I'm trying not to make the overall character sheet size bigger so keeping the amount of info that's visible down, but I can look to squeeze in a view icon if that'd help a lot.  I also dont want to reduce the font size as I struggle enough already.  

Is having a view icon a worthwhile trade off to a larger character sheet (may become a delete icon when the character sheet is unlocked)?

**Comment by Lockbox313** [comment]
I would prefer context menu view in the non edit mode. The less clutter the better.

**Comment by WisdomOfWombats** [comment]
The skill role could be triggered by clicking the percentile number instead of the skill name. Just as an idea. 
But having a separate icon for opening a view is also a nice idea.

**Comment by Genii-Locorum** [comment]
I'll think on this.  Both options have pros and cons.

**Comment by Genii-Locorum** [comment]
I'm going to leave things as they are for now.  I've started work on Characteristic rolls so skill rolls will follow shortly afterwards.  Let's revisit after that.  I'll leave this open for now.

**Comment by Genii-Locorum** [comment]
OK, I've pushed this in to V1.7

Any feedback on this v old approach would be welcomed
