### ISSUE TITLE
Enhancement: If the gaming setting "Hits per Location" is not selected, then the Combat tab on the actor sheet should hide the hit location table

### ISSUE THREAD

**Issue by WisdomOfWombats** [Genii-Locorum/brp#9]
- When the "Hits per Location" option is not selected in the system settings, then showing the Hit Location table is a bit confusing.
- Suggestion: hide the table, if the option is not selected

**Comment by Genii-Locorum** [comment]
My plan was that if you arent using HPL there will be a  single hit location (this will be driven from Cutlure, which is a bigger development and part of character development) to hold wounds/

But now I'm having a different idea, I'll list wounds separately and show which location they relate to.  Let me have a think about it (but if you've got a preference then please shout).

This is likely to be one for over Xmas.

**Comment by WisdomOfWombats** [comment]
Now that you explain it, both ideas seem valid. I am just looking at the sheet and try to guess intentions :)

**Comment by Genii-Locorum** [comment]
I like your idea.  At the moment I'm tinkering with creating Wounds and hiding the HPL section if the option isnt turned on.
